export const properties = [
  {
    title: 'Luxury Apartment in Dubai Marina',
    description:
      'A luxurious 2-bedroom apartment with stunning views of the marina and the sea. Close to restaurants, shops, and public transport.',
    price: 75000,
    currency: 'AED',
    propertyType: 'Apartment',
    address: 'Dubai Marina, Dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    postalCode: '00000',
    coordinates: {
      type: 'Point',
      coordinates: [25.0774, 55.1396],
    },

    bedrooms: 2,
    bathrooms: 2,
    floor: 12,
    parkingSpaces: 1,
    balcony: true,
    garden: false,
    furnished: true,
    image: '',

    isFeatured: true,
  },
  {
    title: 'Modern Penthouse in Downtown Dubai',
    description:
      'A spacious 4-bedroom penthouse with panoramic views of the Burj Khalifa and Downtown Dubai. Private elevator and access to luxury amenities.',
    price: 25000,
    currency: 'AED',
    propertyType: 'Penthouse',
    address: 'Downtown Dubai, Dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    postalCode: '00001',
    coordinates: {
      type: 'Point',
      coordinates: [25.1972, 55.2744],
    },

    bedrooms: 4,
    bathrooms: 5,
    floor: 30,
    parkingSpaces: 2,
    balcony: true,
    garden: false,
    furnished: true,
    image: '',

    isFeatured: true,
  },
  {
    title: 'Beachfront Villa in Palm Jumeirah',
    description:
      'A magnificent 5-bedroom beachfront villa with direct access to the beach, private pool, garden, and panoramic views of the Dubai skyline.',
    price: 12000,
    currency: 'AED',
    propertyType: 'Villa',
    address: 'Palm Jumeirah, Dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    postalCode: '00002',
    coordinates: {
      type: 'Point',
      coordinates: [25.1125, 55.1407],
    },

    bedrooms: 5,
    bathrooms: 6,
    floor: 1,
    parkingSpaces: 4,
    balcony: true,
    garden: true,
    furnished: true,
    image: '',

    isFeatured: false,
  },
  {
    title: 'Contemporary Apartment in Abu Dhabi',
    description:
      "Sleek and modern 2-bedroom apartment located in the heart of Abu Dhabi. Close to the city's best amenities, shopping malls, and cultural centers.",
    price: 45000,
    currency: 'AED',
    propertyType: 'Apartment',
    address: 'Abu Dhabi City, Abu Dhabi',
    city: 'Abu Dhabi',
    state: 'Abu Dhabi',
    country: 'UAE',
    postalCode: '00003',
    coordinates: {
      type: 'Point',
      coordinates: [24.4667, 54.3667],
    },

    bedrooms: 2,
    bathrooms: 2,
    floor: 5,
    parkingSpaces: 1,
    balcony: false,
    garden: false,
    furnished: true,
    image: '',

    isFeatured: false,
  },
  {
    title: 'Luxury Villa in Al Ain',
    description:
      'A stunning 6-bedroom villa with spacious rooms, private pool, and a large garden located in the peaceful city of Al Ain.',
    price: 35000,
    currency: 'AED',
    propertyType: 'Villa',
    address: 'Al Ain, Abu Dhabi',
    city: 'Al Ain',
    state: 'Abu Dhabi',
    country: 'UAE',
    postalCode: '00004',
    coordinates: {
      type: 'Point',
      coordinates: [24.1925, 55.7463],
    },

    bedrooms: 6,
    bathrooms: 7,
    floor: 1,
    parkingSpaces: 3,
    balcony: true,
    garden: true,
    furnished: true,
    image: '',

    isFeatured: true,
  },
  {
    title: 'Studio Apartment in Sharjah',
    description:
      'A budget-friendly studio apartment located in a prime area of Sharjah, close to amenities, shopping malls, and transport.',
    price: 15000,
    currency: 'AED',
    propertyType: 'Apartment',
    address: 'Sharjah, UAE',
    city: 'Sharjah',
    state: 'Sharjah',
    country: 'UAE',
    postalCode: '00005',
    coordinates: {
      type: 'Point',
      coordinates: [25.3468, 55.4131],
    },

    bedrooms: 1,
    bathrooms: 1,
    floor: 3,
    parkingSpaces: 1,
    balcony: false,
    garden: false,
    furnished: false,
    image: '',

    isFeatured: false,
  },
  {
    title: 'Modern 2-Bedroom Apartment in Al Majaz',
    description:
      'A spacious 2-bedroom apartment in the heart of Al Majaz with stunning waterfront views and high-end finishes.',
    price: 80000,
    currency: 'AED',
    propertyType: 'apartment',
    address: 'Al Majaz 3, Sharjah',
    city: 'Sharjah',
    state: 'Sharjah',
    country: 'UAE',
    postalCode: '0000',
    coordinates: {
      type: 'Point',
      coordinates: [55.3994, 25.3575],
    },
    bedrooms: 2,
    bathrooms: 2,
    floor: 5,
    parkingSpaces: 1,
    balcony: true,
    garden: false,
    furnished: true,
    image: '',
    isFeatured: true,
  },
  {
    title: 'Luxurious Villa in Al Barashi',
    description:
      'A beautiful 5-bedroom villa with a private garden and swimming pool, ideal for families looking for comfort and style.',
    price: 150000,
    currency: 'AED',
    propertyType: 'villa',
    address: 'Al Barashi, Sharjah',
    city: 'Sharjah',
    state: 'Sharjah',
    country: 'UAE',
    postalCode: '0001',
    coordinates: {
      type: 'Point',
      coordinates: [55.4785, 25.2487],
    },
    bedrooms: 5,
    bathrooms: 5,
    floor: 1,
    parkingSpaces: 4,
    balcony: true,
    garden: true,
    furnished: false,
    image: '',
    isFeatured: false,
  },
  {
    title: 'Cozy Studio Apartment in Al Qasimia',
    description:
      'Affordable studio apartment in Al Qasimia ideal for singles or couples, close to public transport and shopping centers.',
    price: 35000,
    currency: 'AED',
    propertyType: 'apartment',
    address: 'Al Qasimia, Sharjah',
    city: 'Sharjah',
    state: 'Sharjah',
    country: 'UAE',
    postalCode: '0002',
    coordinates: {
      type: 'Point',
      coordinates: [55.3847, 25.3388],
    },
    bedrooms: 1,
    bathrooms: 1,
    floor: 3,
    parkingSpaces: 1,
    balcony: false,
    garden: false,
    furnished: true,
    image: '',
    isFeatured: false,
  },
  {
    title: 'Spacious 4-Bedroom Townhouse in Al Taawun',
    description:
      'Beautifully designed 4-bedroom townhouse in Al Taawun, ideal for families looking for a comfortable living space with modern amenities.',
    price: 120000,
    currency: 'AED',
    propertyType: 'townhouse',
    address: 'Al Taawun, Sharjah',
    city: 'Sharjah',
    state: 'Sharjah',
    country: 'UAE',
    postalCode: '0003',
    coordinates: {
      type: 'Point',
      coordinates: [55.3871, 25.3245],
    },
    bedrooms: 4,
    bathrooms: 4,
    floor: 2,
    parkingSpaces: 2,
    balcony: true,
    garden: true,
    furnished: false,
    image: '',
    isFeatured: false,
  },
  {
    title: 'Elegant Penthouse in Al Nuaimia',
    description:
      'Luxurious penthouse with panoramic views of Sharjah, featuring 3 bedrooms, a private terrace, and top-tier finishes.',
    price: 250000,
    currency: 'AED',
    propertyType: 'penthouse',
    address: 'Al Nuaimia, Sharjah',
    city: 'Sharjah',
    state: 'Sharjah',
    country: 'UAE',
    postalCode: '0004',
    coordinates: {
      type: 'Point',
      coordinates: [55.4111, 25.306],
    },
    bedrooms: 3,
    bathrooms: 3,
    floor: 6,
    parkingSpaces: 3,
    balcony: true,
    garden: false,
    furnished: true,
    image: '',
    isFeatured: false,
  },
  {
    title: 'Beachfront Villa in Palm Jumeirah',
    description:
      'A magnificent 5-bedroom beachfront villa with direct access to the beach, private pool, garden, and panoramic views of the Dubai skyline.',
    price: 12000,
    currency: 'AED',
    propertyType: 'Villa',
    address: 'Palm Jumeirah, Dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    postalCode: '00002',
    coordinates: {
      type: 'Point',
      coordinates: [25.1125, 55.1407],
    },
    bedrooms: 5,
    bathrooms: 6,
    floor: 1,
    parkingSpaces: 4,
    balcony: true,
    garden: true,
    furnished: true,
    image: '',
    isFeatured: false,
  },
  {
    title: 'Modern Penthouse in Downtown Dubai',
    description:
      'A spacious 4-bedroom penthouse with panoramic views of the Burj Khalifa and Downtown Dubai. Private elevator and access to luxury amenities.',
    price: 25000,
    currency: 'AED',
    propertyType: 'Penthouse',
    address: 'Downtown Dubai, Dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    postalCode: '00001',
    coordinates: {
      type: 'Point',
      coordinates: [25.1972, 55.2744],
    },
    bedrooms: 4,
    bathrooms: 5,
    floor: 30,
    parkingSpaces: 2,
    balcony: true,
    garden: false,
    furnished: true,
    image: '',
    isFeatured: true,
  },
  {
    title: 'Luxury Apartment in Business Bay',
    description:
      'An exquisite 3-bedroom apartment with stunning views of the Dubai Canal. Fully furnished and equipped with state-of-the-art amenities.',
    price: 15000,
    currency: 'AED',
    propertyType: 'Apartment',
    address: 'Business Bay, Dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    postalCode: '00003',
    coordinates: {
      type: 'Point',
      coordinates: [25.1865, 55.2802],
    },
    bedrooms: 3,
    bathrooms: 4,
    floor: 15,
    parkingSpaces: 2,
    balcony: true,
    garden: false,
    furnished: true,
    image: '',
    isFeatured: true,
  },
  {
    title: 'Contemporary Villa in Arabian Ranches',
    description:
      'A beautiful 5-bedroom villa with a private pool, landscaped garden, and large living spaces in the heart of Arabian Ranches.',
    price: 8000,
    currency: 'AED',
    propertyType: 'Villa',
    address: 'Arabian Ranches, Dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    postalCode: '00004',
    coordinates: {
      type: 'Point',
      coordinates: [25.0093, 55.2882],
    },
    bedrooms: 5,
    bathrooms: 6,
    floor: 1,
    parkingSpaces: 3,
    balcony: true,
    garden: true,
    furnished: false,
    image: '',
    isFeatured: false,
  },
  {
    title: 'Skyline Apartment in Jumeirah Beach Residences',
    description:
      'A luxurious 2-bedroom apartment with stunning views of the Arabian Gulf and the Dubai Marina skyline. Fully furnished with premium finishes.',
    price: 11000,
    currency: 'AED',
    propertyType: 'Apartment',
    address: 'Jumeirah Beach Residences, Dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    postalCode: '00005',
    coordinates: {
      type: 'Point',
      coordinates: [25.0715, 55.1418],
    },
    bedrooms: 2,
    bathrooms: 3,
    floor: 8,
    parkingSpaces: 1,
    balcony: true,
    garden: false,
    furnished: true,
    image: '',
    isFeatured: true,
  },
  {
    title: 'Exclusive Villa in Emirates Hills',
    description:
      'An ultra-luxurious 6-bedroom villa with panoramic views of the golf course, private spa, and large outdoor terrace.',
    price: 30000,
    currency: 'AED',
    propertyType: 'Villa',
    address: 'Emirates Hills, Dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    postalCode: '00006',
    coordinates: {
      type: 'Point',
      coordinates: [25.0642, 55.1434],
    },
    bedrooms: 6,
    bathrooms: 7,
    floor: 2,
    parkingSpaces: 5,
    balcony: true,
    garden: true,
    furnished: true,
    image: '',
    isFeatured: true,
  },
  {
    title: 'Serviced Apartment in Dubai Marina',
    description:
      'A 1-bedroom fully serviced apartment with beautiful views of the marina, offering world-class facilities and easy access to restaurants and shops.',
    price: 8500,
    currency: 'AED',
    propertyType: 'Apartment',
    address: 'Dubai Marina, Dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    postalCode: '00007',
    coordinates: {
      type: 'Point',
      coordinates: [25.0783, 55.1331],
    },
    bedrooms: 1,
    bathrooms: 1,
    floor: 4,
    parkingSpaces: 1,
    balcony: true,
    garden: false,
    furnished: true,
    image: '',
    isFeatured: false,
  },
  {
    title: 'Spacious Family Home in The Springs',
    description:
      "A 4-bedroom family home with a large garden, modern finishes, and access to The Springs community's pools and parks.",
    price: 9500,
    currency: 'AED',
    propertyType: 'Villa',
    address: 'The Springs, Dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    postalCode: '00008',
    coordinates: {
      type: 'Point',
      coordinates: [25.0565, 55.2979],
    },
    bedrooms: 4,
    bathrooms: 5,
    floor: 1,
    parkingSpaces: 3,
    balcony: true,
    garden: true,
    furnished: false,
    image: '',
    isFeatured: false,
  },
  {
    title: 'Townhouse in Dubai Hills Estate',
    description:
      'A modern 3-bedroom townhouse with a private garden and easy access to schools, shops, and Dubai Hills Mall.',
    price: 12000,
    currency: 'AED',
    propertyType: 'Townhouse',
    address: 'Dubai Hills Estate, Dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    postalCode: '00009',
    coordinates: {
      type: 'Point',
      coordinates: [25.0843, 55.2595],
    },
    bedrooms: 3,
    bathrooms: 4,
    floor: 2,
    parkingSpaces: 2,
    balcony: true,
    garden: true,
    furnished: true,
    image: '',
    isFeatured: false,
  },
  {
    title: 'Luxury Apartment in Dubai Silicon Oasis',
    description:
      'A 2-bedroom apartment with state-of-the-art finishes, located in the tech hub of Dubai Silicon Oasis.',
    price: 9500,
    currency: 'AED',
    propertyType: 'Apartment',
    address: 'Dubai Silicon Oasis, Dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    postalCode: '00010',
    coordinates: {
      type: 'Point',
      coordinates: [25.0806, 55.3742],
    },
    bedrooms: 2,
    bathrooms: 3,
    floor: 10,
    parkingSpaces: 1,
    balcony: true,
    garden: false,
    furnished: true,
    image: '',
    isFeatured: false,
  },
  {
    title: 'Penthouse in Dubai Opera District',
    description:
      'A stunning 3-bedroom penthouse with panoramic views of the Burj Khalifa, the Dubai Fountain, and the Dubai Opera District.',
    price: 20000,
    currency: 'AED',
    propertyType: 'Penthouse',
    address: 'Opera District, Dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    postalCode: '00011',
    coordinates: {
      type: 'Point',
      coordinates: [25.1931, 55.2701],
    },
    bedrooms: 3,
    bathrooms: 4,
    floor: 35,
    parkingSpaces: 2,
    balcony: true,
    garden: false,
    furnished: true,
    image: '',
    isFeatured: true,
  },
  {
    title: 'Seafront Apartment in Dubai Creek Harbour',
    description:
      'A luxurious 2-bedroom apartment overlooking the Dubai Creek with a large terrace and top-of-the-line finishes.',
    price: 14500,
    currency: 'AED',
    propertyType: 'Apartment',
    address: 'Dubai Creek Harbour, Dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    postalCode: '00012',
    coordinates: {
      type: 'Point',
      coordinates: [25.2257, 55.3087],
    },
    bedrooms: 2,
    bathrooms: 3,
    floor: 10,
    parkingSpaces: 1,
    balcony: true,
    garden: false,
    furnished: true,
    image: '',
    isFeatured: true,
  },
  {
    title: 'Studio Apartment in Jumeirah Lake Towers',
    description:
      'A cozy studio apartment with views of the Jumeirah Lakes and easy access to Dubai Metro.',
    price: 6000,
    currency: 'AED',
    propertyType: 'Apartment',
    address: 'Jumeirah Lake Towers, Dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    postalCode: '00013',
    coordinates: {
      type: 'Point',
      coordinates: [25.0653, 55.1413],
    },
    bedrooms: 1,
    bathrooms: 1,
    floor: 2,
    parkingSpaces: 1,
    balcony: false,
    garden: false,
    furnished: true,
    image: '',
    isFeatured: false,
  },
  {
    title: 'Spacious Villa in Al Barari',
    description:
      'A 5-bedroom villa in the heart of Al Barari with a large garden, private pool, and luxurious interiors.',
    price: 22000,
    currency: 'AED',
    propertyType: 'Villa',
    address: 'Al Barari, Dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    postalCode: '00014',
    coordinates: {
      type: 'Point',
      coordinates: [25.0582, 55.296],
    },
    bedrooms: 5,
    bathrooms: 6,
    floor: 2,
    parkingSpaces: 4,
    balcony: true,
    garden: true,
    furnished: true,
    image: '',
    isFeatured: false,
  },
  {
    title: 'Modern Townhouse in Jumeirah Village Circle',
    description:
      'A 3-bedroom townhouse with spacious rooms, private garden, and easy access to main roads and shopping malls.',
    price: 9000,
    currency: 'AED',
    propertyType: 'Townhouse',
    address: 'Jumeirah Village Circle, Dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    postalCode: '00015',
    coordinates: {
      type: 'Point',
      coordinates: [25.0849, 55.2442],
    },
    bedrooms: 3,
    bathrooms: 4,
    floor: 1,
    parkingSpaces: 2,
    balcony: true,
    garden: true,
    furnished: false,
    image: '',
    isFeatured: true,
  },
];
