name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Heroku
        uses: actions/heroku@1.0.0
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: your-heroku-app-name

      - name: Build and Deploy
        run: |
          cd backend
          docker-compose build
          docker-compose push
          heroku container:push web -a property-portal-backend
          heroku container:release web -a property-portal-backend
